#pragma once

#include <Arduino.h>

//DriveTrain
#define IS_GYRO false
#define IS_DISTANCE_SENSOR true
#define WHEEL_DISTANCE (268.0f / 20.0f)

#define ROBOT_SPEED 0.9f
#define ETALON_DISTANCE 180.0f

#define ANGLE_ERROR 5.0f
#define SINGLE_ENCODER_STEP (20.0f * 24.0f)
#define DIAMETR (116 / 10)

#define BASE_STEP_COUNT 8

#define EXECUTION_LIMIT 2.5f
#define TIME_ERROR 1.0

//Intake
#define CLAMP_SERVO_CALMP_POS 106
#define CLAMP_SERVO_UNCLAMP_POS 90

#define CLAMP_OPEN_TIMER 0.05f

#define SEPARATOR_P 0.042f
#define SEPARATOR_D 0.0f

#define SEPARATOR_MAX_VOLTADGE 9.0
#define SEPARATOR_MOTOR_STEP 720 / 3

#define COLOR_SENSOR_CLAMP_SENS 2600
#define COLOR_SENSOR_SEPARARTOR_SENS 500

#define SEPARATOR_SENS 40

#define BRUSH_SERVO_SPEED 45
#define BRUSH_MOTOR_POWER 1.0f

#define BRUSH_DEFEND_TIMER 1.0f

#define SEPARATOR_DELAY 0.6f

//median filter
#define DEFAULT_MEDIAN_BUFFER_LENGHT 5